// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzczxlbhynqwskunldag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6Y3p4bGJoeW5xd3NrdW5sZGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzQxMzUsImV4cCI6MjA2NjYxMDEzNX0.1Nym9_DcTwfuzlJMQ2q9TH5CDR-AERqiOUgkrWHZROM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);